name: Build and Release

on:
  push:
    tags:
      - '*' # Trigger workflow on tag pushes

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # ARM64 Linux
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: paper-extract
            asset_name: paper-extract-aarch64-linux
          # ARM64 macOS
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: paper-extract
            asset_name: paper-extract-aarch64-darwin
          # x86_64 Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: paper-extract
            asset_name: paper-extract-x86_64-linux
          # x86_64 macOS
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: paper-extract
            asset_name: paper-extract-x86_64-darwin
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Install cross-compilation tools (Linux ARM64)
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
    
    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Create release artifact
      run: |
        mkdir -p artifacts
        cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} artifacts/${{ matrix.asset_name }}
        chmod +x artifacts/${{ matrix.asset_name }}
        cd artifacts && tar czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.asset_name }}
    
    - uses: softprops/action-gh-release@v2
      with:
        files: ./artifacts/${{ matrix.asset_name }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}